# validate YAML
# https://codebeautify.org/yaml-validator

name: github-actions
on: [push]
jobs:
  build-deploy:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/r-lib/actions/tree/master/setup-r
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.3' # The R version to download
      - run: sudo apt-get install libgdal-dev libudunits2-dev
      - run: Rscript -e "install.packages(c('rsconnect', 'shiny', 'tidyverse', 'lubridate', 'shinyWidgets', 'DT', 'plotly', 'readr', 'shinydashboard', 'shinyjs', 'shinyBS', 'leaflet'))"
      - name: Push to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name=${{secrets.SHINYAPPS_NAME}}, token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp()"